name: openwisp2
image: ubuntu/xenial
mode: pull

containers:
  - name: openwisp
    hostnames:
      - openwisp

provisioning:
  - type: ansible
    playbook: playbook.yml
    groups:
      openwisp2:
        - openwisp
    lxd_transport: true